### ISSUE TITLE
Bug: Evictor - unmarshal errors: line 98: mapping key "resources" already defined at line 73

### ISSUE THREAD

**Issue by jz-wilson** [castai/helm-charts#397]
When installing any version of evictor over version `.0.24` it fails with a duplicate error.

```txt
Helm install failed for release castai-agent/castai-evictor with chart castai-evictor@0.24.17: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 98: mapping key "resources" already defined at line 73
```

Looks like there are two fields for resources with the addition of the vpa. So no deployments of evictor will work with .0.24 until this is resolved. I have forced our installations to use the latest working one - `.0.23.57`.

My values for reference:
```yaml
  values:
    dryRun: false
    aggressiveMode: true
    apiKeySecretRef: castai
    managedByCASTAI: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
```
