### ISSUE TITLE
Add the ability to override the service port name

### ISSUE THREAD

**Issue by mmastersvz** [castai/helm-charts#528]
Add into https://github.com/castai/helm-charts/blob/main/charts/castai-pod-node-lifecycle/templates/service.yaml#L9-L16 a variable to override the service port name.

When using istio the current port name results in IST0118.  See https://istio.io/latest/docs/reference/config/analysis/ist0118/#how-to-resolve

[`values.yaml`](https://github.com/castai/helm-charts/blob/main/charts/castai-pod-node-lifecycle/values.yaml)
```yaml
  service:
    portNames:
      https: "https"
      metrics: "metrics"
```

[`service.yaml`](https://github.com/castai/helm-charts/blob/main/charts/castai-pod-node-lifecycle/templates/service.yaml)
```yaml
  ports:
    - name:  {{ .Values.service.portNames.https }}
      protocol: TCP
      port: 443
      targetPort: https
    - name:  {{ .Values.service.portNames.metrics }}
      protocol: TCP
      port: 9090
      targetPort: 9090
```

Then can set it to override to eliminate IST0118

```yaml
  service:
    portNames:
      https: "tcp-https"
      metrics: "tcp-metrics"
```
